# Generated by Django 5.2.6 on 2025-09-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_status_taskupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskupdate',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('ARCHIVED', 'ARCHIVED')], max_length=20, null=True),
        ),
    ]
