# Generated by Django 5.2.6 on 2025-09-11 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_updated_by_taskupdate_created_by_and_more'),
        ('task', '0005_alter_task_priority_alter_task_status_and_more'),
    ]

    operations = [
    ]
