# Generated by Django 5.2.6 on 2025-09-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_merge_20250911_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], max_length=20, null=True),
        ),
    ]
