# Generated by Django 5.2.6 on 2025-09-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_priority_alter_task_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskUpdate',
        ),
    ]
