# Generated by Django 5.2.6 on 2025-09-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_delete_taskupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
