# Generated by Django 5.2.6 on 2025-09-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(blank=True, choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('general', 'General')], max_length=20, null=True),
        ),
    ]
